CREATE DATABASE IF NOT EXISTS hb5;
USE hb5;
CREATE TABLE IF NOT EXISTS User(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
first_name VARCHAR(255),
last_name VARCHAR(255),
email VARCHAR(255) UNIQUE,
password VARCHAR(255),
is_admin BOOL DEFAULT FALSE,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Place(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
title VARCHAR(255),
description TEXT,
price DECIMAL(10, 2),
latitude FLOAT,
longitude FLOAT,
owner_id CHAR(36),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (owner_id) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Review(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
text TEXT,
rating INT,
user_id CHAR(36), 
place_id CHAR(36),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
FOREIGN KEY (place_id) REFERENCES Place(id) ON DELETE CASCADE,
CONSTRAINT Rating_b_1_5  CHECK (rating >= 1 and rating <= 5 ),
CONSTRAINT UC_User_Place UNIQUE (user_id, place_id)
);

CREATE TABLE IF NOT EXISTS Amenity(
id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
name VARCHAR(255) UNIQUE,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Place_Amenity(
place_id CHAR(36),
amenity_id CHAR(36),
PRIMARY KEY (place_id, amenity_id),
FOREIGN KEY (place_id) REFERENCES Place(id) ON DELETE CASCADE,
FOREIGN KEY (amenity_id) REFERENCES Amenity(id) ON DELETE CASCADE
);

INSERT INTO User(id, email, first_name, last_name, password, is_admin)
VALUES ('36c9050e-ddd3-4c3b-9731-9f487208bbc1','admin@hbnb.io','Admin', 'HBnB','$2y$10$WyusWbOrXPEOLfQA78bele4njGC7VkB5ZG95m4is4k2xe58tvxfNq', True);

INSERT INTO Amenity(id, name)
VALUES (UUID(), 'WiFi'),
		(UUID(), 'Swimming Pool'),
		(UUID(), 'Air Conditioning');
		